### ISSUE TITLE
Support for Robolectric 3.7?

### ISSUE THREAD

**Issue by autonomousapps** [hkhc/electricspock#7]
I am trying to update robolectric so I can use aapt2 and Android 3.0. See http://robolectric.org/getting-started/#building-with-gradle

**Comment by hkhc** [comment]
Please try ElectricSpock 0.8.

**Comment by autonomousapps** [comment]
There's a problem.

I've been on ElectricSpock 0.6 for a while and it worked well. I tried bumping to 0.8 and ran into a problem. I tried 0.7 and found the same problem. Here's a stacktrace:
```
java.lang.ExceptionInInitializerError
	at io.reactivex.android.schedulers.AndroidSchedulers$1.call(AndroidSchedulers.java:35)
	at io.reactivex.android.schedulers.AndroidSchedulers$1.call(AndroidSchedulers.java:33)
	at io.reactivex.android.plugins.RxAndroidPlugins.callRequireNonNull(RxAndroidPlugins.java:70)
	at io.reactivex.android.plugins.RxAndroidPlugins.initMainThreadScheduler(RxAndroidPlugins.java:40)
	at io.reactivex.android.schedulers.AndroidSchedulers.<clinit>(AndroidSchedulers.java:32)
	at com.chess.utilities.rx.RxUtil.<clinit>(RxUtil.java:21)
	at com.chess.analytics.AnalyticsCallWrapper.onActivityResumed(AnalyticsCallWrapper.java:108)
	at com.chess.analytics.AnalyticsCallWrapperSpec.calls should not be duplicated because of poor lifecycle management(AnalyticsCallWrapperSpec.groovy:46)
Caused by: java.lang.NullPointerException
	at android.os.Handler.<init>(Handler.java:229)
	at android.os.Handler.<init>(Handler.java:137)
	at io.reactivex.android.schedulers.AndroidSchedulers$MainHolder.<clinit>(AndroidSchedulers.java:29)
	... 8 more
```
You're hitting some code when the following gets initialized:
```
@VisibleForTesting public static Scheduler mainThreadScheduler = AndroidSchedulers.mainThread();
```
It appears to be [this issue](https://stackoverflow.com/questions/43356314/android-rxjava-2-junit-test-getmainlooper-in-android-os-looper-not-mocked-runt), but what I don't understand is why the issue only exists in 0.7+. Any ideas?

**Comment by hkhc** [comment]
@autonomousapps would you please provide a complete steps to reproduce the problem? I created a simple test case and failed to reproduce the problem with Robolectric 3.6.1 and 3.7.1.

**Comment by autonomousapps** [comment]
That would be pretty hard, since my app is ~200k lines of code and it's unclear what exactly the issue is.

I'll give it a try, though.

What does your test case look like, btw?

**Comment by hkhc** [comment]
@autonomousapps I'll show you my test case. Let see if it work for you.

I run it with both Robolectric 3.6.1 and 3.7.1 and ElectricSpock 0.8, and passed.

```
class Issue7Spec extends ElectricSpecification {

    def "Main thread schedule should be available"() {
        given: "A dummy activity"
        def mainActivity = Robolectric.buildActivity(MainActivity).create().get()

        when: "Obtaining a main thread scheduler"
        def sc = AndroidSchedulers.mainThread()

        then: "Scheduler is available"
        sc != null


    }

}
```
